# Data configuration
[data]
dataset_dir = "/data/yash/depth_dataset_without_aug"  # Directory containing the dataset
val_out_dir = "val_out"  # Directory to save validation outputs
# dataset_dir = '/data/yash/sample_dataset/sample_dataset' # dummy dataset
batch_size = 10  # Number of samples in each batch
num_workers = 8  # Number of subprocesses to use for data loading
shuffle = true  # Whether to shuffle the training data
val_freq = 1000

# Model configuration
[model]
type = "VMambaIR"  # Type of model architecture choose in [Uformer, SwinFusion, EMMA,FusionMamba, MambaIR, VMambaIR]
depths = [1, 1, 1, 1, 1, 1, 1, 1, 1]  # Depth of each Uformer block
input_size = 256  
embed_dim = 16  
win_size = 8  
loss = "L1"  # Type of loss function used [L1, Fusionloss_Swin, EMMA_fusion_loss, ERGAS, ERGAS_modified] 
ergas_weight =  1e-4
swin_upscale = 2
swin_depths= [6,6,6,6]
swin_embed_dim = 60
swin_num_heads = [6,6,6,6]
swin_patch_size = 4
fm_channels = 32 # for FusionMamba
fm_spa_channels =3 
fm_spe_channels = 3
fm_H = 256
fm_W = 256
fm_ratio = 1


# Optimizer configuration
[optimizer]
# Choose from ["sgd", "rmsprop", "adam", "nadam"]
type = "adam"  
learning_rate = 0.001 

# Split 300k iterations into two cycles. 
# 1st cycle: fixed 3e-4 LR for 92k iters. 
# 2nd cycle: cosine annealing (3e-4 to 1e-6) for 208k iters.
[scheduler]
type = "CosineAnnealingRestartCyclicLR"  # TODO: Will add support for more later
    [scheduler.params]
    periods = [92000, 208000]  # Periods for the learning rate scheduler
    restart_weights = [1, 1]  # Restart weights for the learning rate scheduler
    eta_mins = [0.0003, 0.000001]  # Minimum learning rates for the learning rate scheduler

# Training configuration
[training]
num_epochs = 100
resume=false
checkpointing_steps = 9000
plot_steps = 10000

# Whether to use Weights and Biases (wandb)
[use_wandb]
value = false
num_sweeps=3

# Default configuration for Weights and Biases (wandb)
[wandb_config_defaults]
epochs = 2  # Default number of epochs for wandb runs
batch_size = 2  # Default batch size for wandb runs
learning_rate = 1e-3  # Default learning rate for wandb runs
optimizer = "adam"  # Default optimizer for wandb runs

# Sweep Configuration
[sweep_config]
method = "random"  # Method for hyperparameter search: grid, random

    [sweep_config.metric]
    name = "val_psnr"  # Metric to optimize during hyperparameter search
    goal = "maximize"  # Goal of the metric: maximize or minimize

    [sweep_config.parameters]
    epochs = {values = [2, 5, 10]}  # Possible values for the number of epochs
    batch_size = {values = [2]}  # Possible values for the batch size
    learning_rate = {values = [0.01, 0.001, 0.0001, 0.0003, 3e-05, 1e-05]}  # Possible values for the learning rate
    optimizer = {values = ["adam", "sgd", "rmsprop"]}  # Possible values for the optimizer
