# Data configuration
[data]
dataset_dir = "/data/yash/depth_dataset_without_aug"  # Directory containing the dataset
val_out_dir = "val_out"  # Directory to save validation outputs
# dataset_dir = '/data/yash/sample_dataset/sample_dataset' # dummy dataset
batch_size = 2  # Number of samples in each batch
num_workers = 8  # Number of subprocesses to use for data loading
shuffle = true  # Whether to shuffle the training data
val_freq = 1000

# Model configuration
[model]
type = "SwinFusion"  # Type of model architecture choose in [Uformer, SwinFusion]
depths = [1, 1, 1, 1, 1, 1, 1, 1, 1]  # Depth of each Uformer block
input_size = 256  
embed_dim = 16  
win_size = 8  
loss = "L1"  # Type of loss function used
swin_upscale = 2
swin_depths= [6,6,6,6]
swin_embed_dim = 60
swin_num_heads = [6,6,6,6]
swin_patch_size = 4


# Optimizer configuration
[optimizer]
# Choose from ["sgd", "rmsprop", "adam", "nadam"]
type = "adam"  
learning_rate = 0.001 

# Training configuration
[training]
num_epochs = 25
resume=true
checkpointing_steps = 1000 

# Whether to use Weights and Biases (wandb)
[use_wandb]
value = false
num_sweeps=3

# Default configuration for Weights and Biases (wandb)
[wandb_config_defaults]
epochs = 2  # Default number of epochs for wandb runs
batch_size = 2  # Default batch size for wandb runs
learning_rate = 1e-3  # Default learning rate for wandb runs
optimizer = "adam"  # Default optimizer for wandb runs

# Sweep Configuration
[sweep_config]
method = "random"  # Method for hyperparameter search: grid, random

    [sweep_config.metric]
    name = "val_psnr"  # Metric to optimize during hyperparameter search
    goal = "maximize"  # Goal of the metric: maximize or minimize

    [sweep_config.parameters]
    epochs = {values = [2, 5, 10]}  # Possible values for the number of epochs
    batch_size = {values = [4, 6, 8, 12]}  # Possible values for the batch size
    learning_rate = {values = [0.01, 0.001, 0.0001, 0.0003, 3e-05, 1e-05]}  # Possible values for the learning rate
    optimizer = {values = ["adam", "sgd", "rmsprop"]}  # Possible values for the optimizer
