image_path: dataset/Flickr24K
scattering_dict:
  Flare7k_scattering: dataset/Flare7Kpp/Flare7K/Scattering_Flare/Compound_Flare
  Real_scattering1: dataset/Flare7Kpp/Flare-R/Compound_Flare
reflective_dict: 
  Flare7k_reflective: dataset/Flare7Kpp/Flare7K/Reflective_Flare
  Real_reflective1: ~
light_dict:
  Flare7k_light: dataset/Flare7Kpp/Flare7K/Scattering_Flare/Light_Source
  Real_light1: dataset/Flare7Kpp/Flare-R/Light_Source
data_ratio: [0.5, 0.5] # or [0.6, 0.4], only a ratio is enough
transform_base:
  img_size: 512
transform_flare:
  scale_min: 0.7
  scale_max: 1.2
  translate: 100
  shear: 20
mask_type: ~


# data loader
use_shuffle: true
num_worker_per_gpu: 4
batch_size_per_gpu: 2
dataset_enlarge_ratio: 1
prefetch_mode: ~